# Generated by Django 5.2.5 on 2025-08-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('subscription_plan', models.CharField(choices=[('Базовый', 'Базовый'), ('Стандарт', 'Стандарт'), ('Премиум', 'Премиум'), ('Не активна', 'Не активна')], default='Не активна', max_length=50, verbose_name='Тариф поддержки')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Подписка активна до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бота')),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp')], max_length=50, verbose_name='Платформа')),
                ('token', models.CharField(max_length=255, verbose_name='API Токен (бота)')),
                ('api_auth_token', models.CharField(max_length=255, unique=True, verbose_name='Токен авторизации API (системный)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='main.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_data', models.TextField(verbose_name='Данные заявки (телефон, бизнес, задача)')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В работе', 'В работе'), ('Завершена', 'Завершена'), ('Отклонена', 'Отклонена')], default='Новая', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='main.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Заявка (Лид)',
                'verbose_name_plural': 'Заявки (Лиды)',
                'ordering': ['-created_at'],
            },
        ),
    ]
